const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const {randomBytes}=require('node:crypto');
const {adapters,ProviderError}=require('./lib/providers');
const {validateProvisioning}=require('./lib/provisioning');
const {isStaleInventoryError}=require('./lib/inventory');
if(process.env.BASE_URL){process.env.BASE_URL=process.env.BASE_URL.trim().replace(/\/+$/,'');process.env.PUBLIC_BASE_URL=new URL('/',process.env.BASE_URL).href;process.env.FLEET_BOOTSTRAP_URL=new URL('/provision/bootstrap.sh',process.env.BASE_URL).href;process.env.FLEET_AGENT_JS_URL=new URL('/provision/agent.js',process.env.BASE_URL).href}
if(!process.env.FLEET_AGENT_TOKEN)process.env.FLEET_AGENT_TOKEN=randomBytes(32).toString('hex');
const PORT=Number(process.env.PORT||4173),root=path.join(__dirname,'public'),providers=adapters();
const agentTargets=new Map(),hyperstackProvisioning=new Map(),instanceRuntime=new Map(),pushedTelemetry=new Map(),telemetryDiagnostics=new Map(),instanceTelemetryKeys=new Map(),lifecycleActions=new Map(),benchmarkJobs=new Map();
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)reject(Error('请求体过大'))});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(Object.assign(Error('JSON 格式错误'),{status:400}))}})})}
function provider(name){const p=providers[name];if(!p)throw Object.assign(Error('未知供应商'),{status:400});return p}
async function all(method,...args){const result=await Promise.allSettled(Object.values(providers).map(p=>p[method](...args)));const data=[],errors=[];result.forEach((r,i)=>{const p=Object.values(providers)[i];if(r.status==='fulfilled')data.push(...r.value);else errors.push({provider:p.name,error:r.reason.message})});return{data,errors}}
async function proxyAgent(instanceId,pathname,method='GET'){const base=agentTargets.get(instanceId);if(!base)throw Object.assign(Error('尚未配置该实例的 agent URL；请在供应商安全隧道中注册 agent 地址'),{status:409});const r=await fetch(new URL(pathname,base),{method,headers:{authorization:`Bearer ${process.env.FLEET_AGENT_TOKEN}`},signal:AbortSignal.timeout(method==='POST'?600000:130000)});if(!r.ok)throw Error(`agent ${r.status}`);return r.json()}
setInterval(async()=>{const cutoff=Date.now()-20*60*1000;for(const [token,pending] of hyperstackProvisioning)if(pending.createdAt<cutoff){hyperstackProvisioning.delete(token);try{await providers.hyperstack.action(pending.id,'delete');instanceRuntime.set(pending.id,{status:'failed',reason:'自动装机超时，实例已删除'})}catch(error){console.error('Hyperstack 超时实例自动删除失败',pending.id,error.message)}}},60000).unref();
async function api(req,res,url){
  if(req.method==='GET'&&url.pathname==='/api/config/status'){const base=process.env.BASE_URL;return json(res,200,{providers:Object.entries(providers).map(([id,p])=>({id,name:p.name,configured:Boolean(p.token),provisioningReady:validateProvisioning(id,process.env).length===0,missing:validateProvisioning(id,process.env)})),runtime:{image:process.env.FLEET_CONTAINER_IMAGE||'nvcr.io/nvidia/pytorch:26.03-py3',os:'Ubuntu 24.04',cuda:'13.2'},controlPlane:base?{baseUrl:new URL('/',base).href,bootstrap:new URL('/provision/bootstrap.sh',base).href,telemetry:new URL('/api/agent/telemetry',base).href,telemetryAgent:new URL('/provision/telemetry.py',base).href}:null})}
  if(req.method==='POST'&&url.pathname==='/api/provision/hyperstack-status'){const d=await body(req),pending=hyperstackProvisioning.get(d.token);if(!pending)throw Object.assign(Error('provision token 无效或已过期'),{status:404});const phases={checking_registry:'正在检查 NGC 镜像仓库',pulling_image:'正在下载容器镜像',image_pulled:'镜像下载完成',validating_cuda:'正在验证 CUDA 与 PyTorch',starting_runtime:'正在启动运行环境',installing_dependencies:'正在安装实例工具',starting_agent:'正在启动监控 Agent'};if(phases[d.status]){const runtime={status:'provisioning',phase:d.status,phaseLabel:phases[d.status],message:d.message||'',updatedAt:new Date().toISOString(),containerImage:d.containerImage};instanceRuntime.set(pending.id,runtime);return json(res,200,{ok:true,runtime})}if(d.status==='failed'){const reason=d.message||'自动装机失败，实例已自动删除';instanceRuntime.set(pending.id,{status:'failed',phase:'failed',phaseLabel:'装机失败',reason,updatedAt:new Date().toISOString()});await providers.hyperstack.action(pending.id,'delete');hyperstackProvisioning.delete(d.token);return json(res,200,{ok:true,deleted:true})}if(d.status==='ready'){const runtime={status:'ready',phase:'ready',phaseLabel:'运行环境已就绪',cudaLabel:d.cudaLabel,driver:d.driver,containerImage:d.containerImage,requirementMet:String(d.cudaLabel||'').includes('13.'),updatedAt:new Date().toISOString()};instanceRuntime.set(pending.id,runtime);hyperstackProvisioning.delete(d.token);return json(res,200,{ok:true,runtime})}throw Object.assign(Error('未知 provision 状态'),{status:400})}
  if(req.method==='GET'&&url.pathname==='/api/offers'){const r=await all('listOffers');return json(res,200,{offers:r.data,errors:r.errors,updatedAt:new Date().toISOString(),live:true,regionalInventoryPreloaded:false})}
  if(req.method==='POST'&&url.pathname==='/api/agent/telemetry'){const d=await body(req),key=d.provider&&d.instanceName?`${d.provider}:${d.instanceName}`:null;if(process.env.FLEET_AGENT_TOKEN&&req.headers.authorization!==`Bearer ${process.env.FLEET_AGENT_TOKEN}`){if(key)telemetryDiagnostics.set(key,{state:'auth_failed',at:Date.now()});throw Object.assign(Error('unauthorized'),{status:401})}if(!key||!Array.isArray(d.telemetry?.gpus))throw Object.assign(Error('遥测数据格式错误'),{status:400});if(d.telemetry.runtime?.phase==='starting')d.telemetry.runtime={...d.telemetry.runtime,status:'ready',phase:'telemetry_ready',phaseLabel:'GPU 遥测已连接'};pushedTelemetry.set(key,{at:Date.now(),data:d.telemetry});telemetryDiagnostics.set(key,{state:'connected',at:Date.now()});const canRunJobs=Array.isArray(d.capabilities)&&d.capabilities.includes('agent_jobs'),job=canRunJobs?[...benchmarkJobs.values()].find(x=>x.instanceKey===key&&x.status==='queued'):null;if(job){job.status='running';job.startedAt=Date.now()}return json(res,202,{ok:true,job:job?{id:job.id,type:job.type,params:job.params}:null})}
  if(req.method==='POST'&&url.pathname==='/api/agent/job-result'){if(process.env.FLEET_AGENT_TOKEN&&req.headers.authorization!==`Bearer ${process.env.FLEET_AGENT_TOKEN}`)throw Object.assign(Error('unauthorized'),{status:401});const d=await body(req),job=benchmarkJobs.get(String(d.jobId));if(!job)throw Object.assign(Error('agent job not found'),{status:404});if(job.instanceKey!==`${d.provider}:${d.instanceName}`)throw Object.assign(Error('agent job instance mismatch'),{status:403});job.status=d.status==='completed'?'completed':'failed';job.completedAt=Date.now();job.report=d.result||null;job.error=d.error||null;return json(res,202,{ok:true})}
  if(req.method==='GET'&&url.pathname==='/api/providers/ppio/regional-inventory')return json(res,200,{offers:await providers.ppio.listOffersWithRegions(url.searchParams.get('refresh')==='1'),updatedAt:new Date().toISOString()});
  if(req.method==='GET'&&url.pathname==='/api/instances'){const r=await all('listInstances'),pendingIds=new Set([...hyperstackProvisioning.values()].map(x=>String(x.id))),seen=new Set(r.data.map(x=>String(x.id)));for(const [id,pending] of lifecycleActions){const current=r.data.find(x=>String(x.id)===id),done=!current&&pending.action==='delete'||current&&pending.action==='stop'&&current.status==='stopped'||current&&pending.action==='start'&&current.status==='running';if(done||Date.now()-pending.at>120000)lifecycleActions.delete(id)}for(const [id,pending] of lifecycleActions)if(pending.action==='delete'&&!seen.has(id))lifecycleActions.delete(id);for(const x of r.data){if(x.agentUrl)agentTargets.set(String(x.id),x.agentUrl);instanceTelemetryKeys.set(String(x.id),`${x.provider}:${x.name}`)}return json(res,200,{instances:r.data.map(x=>{const storedRuntime=instanceRuntime.get(String(x.id))||instanceRuntime.get(x.id),pending=pendingIds.has(String(x.id)),key=instanceTelemetryKeys.get(String(x.id)),diagnostic=telemetryDiagnostics.get(key),pushed=pushedTelemetry.get(key),telemetryConnected=Boolean(pushed&&Date.now()-pushed.at<15000),telemetryRuntime=pushed?.data?.runtime,runtime=storedRuntime||telemetryRuntime,action=lifecycleActions.get(String(x.id)),initializing=telemetryRuntime?.status==='provisioning'&&!telemetryConnected,status=action?.action==='stop'?'stopping':action?.action==='start'?'provisioning':action?.action==='delete'?'terminating':(pending||storedRuntime?.status==='provisioning'||initializing)?'provisioning':telemetryRuntime?.status==='failed'?'failed':x.status,benchmarkReady=telemetryConnected||agentTargets.has(String(x.id));return{...x,status,runtime,cudaProfile:runtime?.cudaLabel||x.cudaProfile,telemetryStatus:telemetryConnected?'connected':diagnostic?.state||'waiting',telemetryLastSeen:pushed?.at?new Date(pushed.at).toISOString():undefined,benchmarkReady,benchmarkMessage:benchmarkReady?(telemetryConnected?'Agent 反向测试通道已就绪':'Agent 直连测试通道已就绪'):'等待 Agent 上线后即可测试',raw:undefined}}),errors:r.errors})}
  const discovery=url.pathname.match(/^\/api\/providers\/([^/]+)\/discovery$/);if(req.method==='GET'&&discovery)return json(res,200,await provider(discovery[1]).discover());
  const regional=url.pathname.match(/^\/api\/providers\/ppio\/products\/([^/]+)\/regions$/);if(req.method==='GET'&&regional)return json(res,200,{regions:await providers.ppio.listRegionalOffers(decodeURIComponent(regional[1])),updatedAt:new Date().toISOString()});
  if(req.method==='POST'&&url.pathname==='/api/instances'){const d=await body(req);if(d.offerId&&(!d.provider||!d.productId)){const [p,...parts]=d.offerId.split(':');d.provider=p;d.productId=parts.join(':')}if(!d.provider||!d.productId)throw Object.assign(Error('provider 与 productId 必填'),{status:400});if(d.provider==='hyperstack')d.provisionToken=randomBytes(24).toString('hex');let item;try{item=await provider(d.provider).create(d)}catch(error){if(isStaleInventoryError(error))throw Object.assign(Error('当前页面的库存信息已过期，该 GPU 可能已被其他用户抢先创建，请刷新后重试'),{status:409,code:'stale_inventory',provider:d.provider});throw error}if(d.provisionToken)hyperstackProvisioning.set(d.provisionToken,{id:item.id,createdAt:Date.now()});return json(res,202,item)}
  const action=url.pathname.match(/^\/api\/instances\/([^/]+)\/(start|stop|delete)$/);if(req.method==='POST'&&action){const d=await body(req),id=decodeURIComponent(action[1]),operation=action[2];try{await provider(d.provider).action(id,operation)}catch(error){const text=`${error.message||''} ${JSON.stringify(error.details||{})}`;if(operation==='start'&&/capacity|insufficient|out.?of.?stock|no.?stock|unavailable|not.?available|sold.?out|inventory|resource.*(?:exhaust|short)|容量不足|库存不足|无库存|资源不足/i.test(text))throw Object.assign(Error('原资源池暂时没有可用容量，请稍后重试或自行选择其他资源'),{status:409,code:'capacity_unavailable',provider:d.provider});throw error}lifecycleActions.set(String(id),{action:operation,at:Date.now()});return json(res,202,{ok:true,status:operation==='stop'?'stopping':operation==='start'?'provisioning':'terminating'})}
  const register=url.pathname.match(/^\/api\/instances\/([^/]+)\/agent$/);if(req.method==='POST'&&register){const d=await body(req);if(!/^https?:\/\//.test(d.url||''))throw Object.assign(Error('agent url 无效'),{status:400});agentTargets.set(decodeURIComponent(register[1]),d.url);return json(res,200,{ok:true})}
  const telemetry=url.pathname.match(/^\/api\/instances\/([^/]+)\/telemetry$/);if(req.method==='GET'&&telemetry){const id=decodeURIComponent(telemetry[1]);res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'});const send=async()=>{try{const pushed=pushedTelemetry.get(instanceTelemetryKeys.get(String(id)));const data=pushed&&Date.now()-pushed.at<15000?pushed.data:await proxyAgent(id,'/telemetry');res.write(`data: ${JSON.stringify(data)}\n\n`)}catch(e){res.write(`event: error\ndata: ${JSON.stringify({error:e.message})}\n\n`)}};await send();const t=setInterval(send,2000);req.on('close',()=>clearInterval(t));return}
  const benchStatus=url.pathname.match(/^\/api\/instances\/([^/]+)\/benchmark\/jobs\/([^/]+)$/);if(req.method==='GET'&&benchStatus){const id=decodeURIComponent(benchStatus[1]),job=benchmarkJobs.get(decodeURIComponent(benchStatus[2]));if(!job||job.instanceId!==id)throw Object.assign(Error('benchmark job not found'),{status:404});if(job.status==='running'&&Date.now()-job.startedAt>10*60*1000){job.status='failed';job.error='测试超过 10 分钟，已标记失败'}return json(res,200,{id:job.id,status:job.status,mode:job.mode,report:job.report,error:job.error})}
  const bench=url.pathname.match(/^\/api\/instances\/([^/]+)\/benchmark$/);if(bench){const id=decodeURIComponent(bench[1]);if(req.method==='POST'){const d=await body(req),key=instanceTelemetryKeys.get(String(id)),pushed=pushedTelemetry.get(key),connected=Boolean(pushed&&Date.now()-pushed.at<15000);if(connected){const active=[...benchmarkJobs.values()].find(x=>x.instanceId===id&&['queued','running'].includes(x.status));if(active)throw Object.assign(Error('该实例已有测试正在运行'),{status:409});const mode=d.mode==='full'?'full':'quick',job={id:randomBytes(12).toString('hex'),type:'benchmark',params:{mode},instanceId:id,instanceKey:key,mode,status:'queued',createdAt:Date.now()};benchmarkJobs.set(job.id,job);return json(res,202,{queued:true,jobId:job.id,status:job.status,mode:job.mode})}const report=await proxyAgent(id,'/benchmark','POST');return json(res,200,{report})}const report=await proxyAgent(id,'/benchmark');return json(res,200,report)}
  const reachability=url.pathname.match(/^\/api\/instances\/([^/]+)\/reachability$/);if(reachability){const report=await proxyAgent(decodeURIComponent(reachability[1]),'/reachability',req.method==='POST'?'POST':'GET');return json(res,200,report)}
  return json(res,404,{error:'Not found'});
}
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/provision/hyperstack.sh'){res.writeHead(200,{'content-type':'text/x-shellscript; charset=utf-8','cache-control':'no-store'});return fs.createReadStream(path.join(__dirname,'agent','hyperstack.sh')).pipe(res)}if(req.method==='GET'&&url.pathname==='/provision/bootstrap.sh'){res.writeHead(200,{'content-type':'text/x-shellscript; charset=utf-8','cache-control':'no-store'});return fs.createReadStream(path.join(__dirname,'agent','bootstrap.sh')).pipe(res)}if(req.method==='GET'&&url.pathname==='/provision/agent.js'){res.writeHead(200,{'content-type':'text/javascript; charset=utf-8','cache-control':'no-store'});return fs.createReadStream(path.join(__dirname,'agent','agent.js')).pipe(res)}if(req.method==='GET'&&url.pathname==='/provision/telemetry.py'){res.writeHead(200,{'content-type':'text/x-python; charset=utf-8','cache-control':'no-store'});return fs.createReadStream(path.join(__dirname,'agent','telemetry.py')).pipe(res)}if(url.pathname.startsWith('/api/'))return await api(req,res,url);const requested=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));const file=path.resolve(root,requested);if(!file.startsWith(path.resolve(root)+path.sep)&&file!==path.join(root,'index.html'))return json(res,403,{error:'Forbidden'});const stat=await fs.promises.stat(file).catch(()=>null);if(!stat?.isFile())return json(res,404,{error:'Not found'});const type={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'}[path.extname(file)]||'application/octet-stream';res.writeHead(200,{'content-type':type});fs.createReadStream(file).pipe(res)}catch(e){const status=e.status||(e instanceof ProviderError?e.status:500);json(res,status,{error:e.message,code:e.code,provider:e.provider,details:process.env.NODE_ENV==='development'?e.details:undefined})}}).listen(PORT,()=>console.log(`GPU Fleet Console: http://localhost:${PORT}`));
