const { NGC_IMAGE, providerEnvironmentVariables } = require('../../provisioning');
const { runpodStartupCommand } = require('./startup');
const { ProviderError, call, normalizeStatus, authRequired } = require('../common/http');

class RunPodAdapter {
  constructor(env){this.env=env;this.name='RunPod';this.base=env.RUNPOD_API_BASE||'https://rest.runpod.io/v1/';this.graphql=env.RUNPOD_GRAPHQL_BASE||'https://api.runpod.io/';this.token=env.RUNPOD_API_KEY;}
  headers(){return{authorization:`Bearer ${authRequired(this.name,this.token,'RUNPOD_API_KEY')}`,'content-type':'application/json'};}
  async accountBalance(){const query=`query FleetAccountBalance { myself { clientBalance } }`;const r=await call(this.name,this.graphql,'/graphql',{method:'POST',headers:this.headers(),body:{query}});if(r.errors?.length)throw new ProviderError(this.name,r.errors[0].message,502,r.errors);const amount=Number(r.data?.myself?.clientBalance);if(!Number.isFinite(amount))throw new ProviderError(this.name,'RunPod 账户响应缺少余额',502,r);return{amount,currency:'USD',source:'api'};}
  async listOffers(){const query=`query FleetGpuTypes { gpuTypes { id displayName memoryInGb lowestPrice(input: { gpuCount: 1, secureCloud: true }) { stockStatus uninterruptablePrice availableGpuCounts } } }`;const r=await call(this.name,this.graphql,'/graphql',{method:'POST',headers:this.headers(),body:{query}});if(r.errors?.length)throw new ProviderError(this.name,r.errors[0].message,502,r.errors);return(r.data?.gpuTypes||[]).filter(x=>x.id.startsWith('NVIDIA ')).map(x=>({id:`runpod:${x.id}`,provider:'runpod',providerName:this.name,productId:x.id,gpu:x.displayName||x.id,gpuCount:1,vram:x.memoryInGb,region:'Secure Cloud 自动调度',price:Number(x.lowestPrice?.uninterruptablePrice||0),priceUnit:'USD/hour',available:x.lowestPrice?.stockStatus==='High'||(x.lowestPrice?.availableGpuCounts||[]).length>0,inventory:x.lowestPrice?.stockStatus,source:'live'}));}
  async discover(){return{provider:'runpod',products:await this.listOffers(),selectionRequired:['productId'],defaults:{cloudType:'SECURE',imageName:NGC_IMAGE,cuda:'13.0',ports:['3000/http']}}}
  async listInstances(){const pods=await call(this.name,this.base,'pods',{headers:this.headers(),query:{computeType:'GPU',includeMachine:true}});return(pods||[]).filter(x=>x.desiredStatus!=='TERMINATED').map(x=>{const mappings=x.portMappings||x.runtime?.ports||{},wanted=Number(this.env.FLEET_SSH_PORT||22022),mapping=Array.isArray(mappings)?mappings.find(p=>Number(p.privatePort||p.containerPort||p.internalPort||p.port)===wanted):undefined,externalPort=Array.isArray(mappings)?Number(mapping?.publicPort||mapping?.externalPort||mapping?.hostPort):Number(mappings[String(wanted)]);return{id:x.id,provider:'runpod',providerName:this.name,name:x.name,providerRenameSupported:true,providerRenameWarning:'修改运行中的 RunPod 可能触发 Pod 重置，请先保存非持久化数据。',status:normalizeStatus(x.desiredStatus),gpu:x.gpu?.displayName||x.machine?.gpuDisplayName,gpuCount:x.gpu?.count||x.machine?.minPodGpuCount||1,region:x.machine?.dataCenterId||x.machine?.location,image:x.image,price:Number(x.adjustedCostPerHr||x.costPerHr||0),priceUnit:'USD/hour',agentUrl:`https://${x.id}-3000.proxy.runpod.net`,sshHost:x.publicIp||x.publicIP||x.machine?.publicIp,sshPort:externalPort||undefined,sshUser:'root',raw:x}});}
  async create(o){const env=Object.fromEntries(providerEnvironmentVariables(this.env).map(({key,value})=>[key,value])),sshPort=Number(this.env.FLEET_SSH_PORT||22022);env.FLEET_SSH_PORT=String(sshPort);env.FLEET_SSH_PUBLIC_KEY=o.sshPublicKey;env.FLEET_SSH_USER='root';env.FLEET_EXPECTED_CUDA_MAJOR=String(o.expectedCudaMajor||13);if(o.startupScript)env.FLEET_STARTUP_SCRIPT_B64=Buffer.from(o.startupScript,'utf8').toString('base64');const provisionEnv={...this.env,...env},body={name:o.name||'fast-gpu',cloudType:o.cloudType||'SECURE',computeType:'GPU',containerDiskInGb:o.rootfsSize||100,volumeInGb:o.volumeSize||100,volumeMountPath:'/workspace',imageName:o.imageUrl||NGC_IMAGE,allowedCudaVersions:[`${o.expectedCudaMajor||13}.0`],gpuCount:o.gpuCount||1,gpuTypeIds:[o.productId],gpuTypePriority:'custom',interruptible:Boolean(o.spot),globalNetworking:false,supportPublicIp:true,ports:['3000/http',`${sshPort}/tcp`],env,dockerEntrypoint:['bash','-lc'],dockerStartCmd:[runpodStartupCommand(provisionEnv,{sshPublicKey:o.sshPublicKey})],minDiskBandwidthMBps:o.minDiskBandwidthMBps||500,minDownloadMbps:o.minDownloadMbps||100};const r=await call(this.name,this.base,'pods',{method:'POST',headers:this.headers(),body});return{id:r.id,provider:'runpod',name:r.name||body.name,status:normalizeStatus(r.desiredStatus||'RUNNING'),image:r.image||body.imageName,price:Number(r.adjustedCostPerHr||r.costPerHr||0),provisioning:'automatic-container',agentUrl:`https://${r.id}-3000.proxy.runpod.net`};}
  renameInstance(id,name){return call(this.name,this.base,`pods/${encodeURIComponent(id)}/update`,{method:'POST',headers:this.headers(),body:{name}});}
  action(id,action){if(action==='delete')return call(this.name,this.base,`pods/${encodeURIComponent(id)}`,{method:'DELETE',headers:this.headers()});return call(this.name,this.base,`pods/${encodeURIComponent(id)}/${action}`,{method:'POST',headers:this.headers()});}
}


module.exports = { RunPodAdapter };
