const DEFAULT_TIMEOUT = 30000;
const {NGC_IMAGE,bootstrapCommand,ppioEnvs,shellQuote,serviceUrl}=require('./provisioning');

class ProviderError extends Error {
  constructor(provider, message, status = 502, details) {
    super(message); this.name = 'ProviderError'; this.provider = provider; this.status = status; this.details = details;
  }
}

async function call(provider, base, pathname, { method = 'GET', headers = {}, body, query } = {}) {
  const url = new URL(pathname, base);
  if(provider==='Hyperstack'&&method==='POST'&&pathname==='core/virtual-machines'&&body?.security_rules){const port=Number(process.env.FLEET_SSH_PORT||22);body.security_rules=body.security_rules.map(rule=>({...rule,port_range_min:port,port_range_max:port}))}
  if (query) for (const [k, v] of Object.entries(query)) if (v !== undefined) url.searchParams.set(k, String(v));
  const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), DEFAULT_TIMEOUT);
  try {
    const response = await fetch(url, { method, headers: { accept: 'application/json', ...headers }, body: body === undefined ? undefined : JSON.stringify(body), signal: controller.signal });
    const text = await response.text(); let data;
    try { data = text ? JSON.parse(text) : {}; } catch { data = { raw: text.slice(0, 1000) }; }
    if (!response.ok) {const reason=data?.reason||data?.data?.message||data?.data?.reason||data?.error?.message||data?.message||data?.msg||data?.error;console.error(`${provider} API 请求失败`,response.status,JSON.stringify(data));throw new ProviderError(provider, `${provider} API ${response.status}${reason?`: ${typeof reason==='string'?reason:JSON.stringify(reason)}`:''}`, response.status, data);}
    if (data?.code && !['Success', 0, 200].includes(data.code)) throw new ProviderError(provider, data.message || data.msg || `${provider} API error`, 502, data);
    return data;
  } catch (error) {
    if (error instanceof ProviderError) throw error;
    throw new ProviderError(provider, error.name === 'AbortError' ? `${provider} API timeout` : error.message, 502);
  } finally { clearTimeout(timer); }
}

const normalizeStatus = value => ({ Running:'running', Stopped:'stopped', Starting:'provisioning', Initializing:'provisioning', PullingImage:'provisioning', Pending:'provisioning', RUNNING:'running', ACTIVE:'running', EXITED:'stopped', SHUTOFF:'stopped', HIBERNATED:'stopped', CREATING:'provisioning', BUILD:'provisioning', PENDING:'provisioning', TERMINATED:'terminated', running:'running', exited:'stopped', stopped:'stopped', pending:'provisioning', toCreate:'provisioning', creating:'provisioning', pulling:'provisioning', toStart:'provisioning', starting:'provisioning', toRestart:'provisioning', restarting:'provisioning', toReset:'provisioning', resetting:'provisioning', migrating:'provisioning', toStop:'stopping', stopping:'stopping', toRemove:'terminating', removing:'terminating', removed:'terminated' }[value] || String(value || 'unknown').toLowerCase());
const authRequired = (name, value, envName) => { if (!value) throw new ProviderError(name, `缺少服务端环境变量 ${envName}`, 503); return value; };
const ppioPriceToCny = value => Number(value || 0) / 100000;
async function mapLimit(items,limit,fn){const out=new Array(items.length);let next=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(next<items.length){const i=next++;out[i]=await fn(items[i],i)}}));return out;}

class PpioAdapter {
  constructor(env) { this.env=env;this.name='PPIO 派欧云'; this.base=env.PPIO_API_BASE || 'https://api.ppio.com'; this.token=env.PPIO_API_KEY;this.offerCache=null;this.offerLoading=null; }
  headers() { return { authorization:`Bearer ${authRequired(this.name,this.token,'PPIO_API_KEY')}`, 'content-type':'application/json' }; }
  async listBaseOffers() { const r=await call(this.name,this.base,'/gpu-instance/openapi/v1/products',{headers:this.headers()}); return (r.data||[]).map(p=>{const regions=Array.isArray(p.regions)?p.regions:[];return{id:`ppio:${p.id}`,provider:'ppio',providerName:this.name,productId:p.id,gpu:p.name,gpuCount:1,cpu:p.cpuPerGpu,ram:p.memoryPerGpu,diskMin:p.minRootFS,diskMax:p.maxRootFS,regions,region:regions.length?`${regions.length} 个可用地区`:'全部可用地区',price:ppioPriceToCny(p.price),priceRaw:p.price,priceUnit:'CNY/hour',billingMethods:p.billingMethods,source:'live'}}); }
  async listClusters(){const r=await call(this.name,this.base,'/gpu-instance/openapi/v1/clusters',{headers:this.headers()});return r.data||[];}
  async listOffers(){return this.listBaseOffers();}
  async listOffersWithRegions(force=false){if(!force&&this.offerCache&&Date.now()-this.offerCache.at<30000)return this.offerCache.data;if(this.offerLoading)return this.offerLoading;this.offerLoading=(async()=>{const [products,clusters]=await Promise.all([this.listBaseOffers(),this.listClusters()]);const clusterResults=await mapLimit(clusters,5,async cluster=>{try{const r=await call(this.name,this.base,'/gpu-instance/openapi/v1/products',{headers:this.headers(),query:{clusterId:cluster.id,gpuNum:1}});return{cluster,products:r.data||[]}}catch(error){return{cluster,products:[],error:error.message}}});for(const product of products){product.regionalOffers=clusterResults.map(({cluster,products:items,error})=>{const p=items.find(x=>x.id===product.productId);return{clusterId:cluster.id,region:cluster.name,supported:Boolean(p),inventory:error?'unknown':p?.inventoryState||'none',deployable:Boolean(p?.availableDeploy),available:Boolean(p)&&p.inventoryState!=='none',price:ppioPriceToCny(p?.price),priceRaw:p?.price,error}}).filter(x=>x.supported||x.error);product.regions=product.regionalOffers.map(x=>x.region);product.region=`${product.regionalOffers.length} 个可用地区`;}this.offerCache={at:Date.now(),data:products};return products;})();try{return await this.offerLoading}finally{this.offerLoading=null}}
  async listRegionalOffers(productId){const product=(await this.listOffersWithRegions()).find(x=>x.productId===productId);if(!product)throw new ProviderError(this.name,'GPU 产品不存在',404);return product.regionalOffers;}
  async discover(){const [products,baseImages,privateImages]=await Promise.all([this.listOffers(),call(this.name,this.base,'/gpu-instance/openapi/v1/images',{headers:this.headers(),query:{type:'base',pageSize:100,pageNum:1}}),call(this.name,this.base,'/gpu-instance/openapi/v1/images',{headers:this.headers(),query:{type:'private',pageSize:100,pageNum:1}})]);return{provider:'ppio',products,images:[...(baseImages.data||[]).map(x=>({...x,type:'base'})),...(privateImages.data||[]).map(x=>({...x,type:'private'}))],selectionRequired:['productId'],defaults:{imageUrl:'nvcr.io/nvidia/pytorch:26.03-py3'}}}
  async listInstances(){const r=await call(this.name,this.base,'/gpu-instance/openapi/v1/gpu/instances',{headers:this.headers(),query:{pageSize:100,pageNum:1}}),offers=this.offerCache?.data||[],normalize=value=>String(value||'').toLowerCase().replace(/nvidia|geforce|\s|-/g,'');return (r.instances||[]).map(x=>{const productId=x.productId||x.productID||x.product?.id,clusterId=x.clusterId||x.clusterID||x.cluster?.id,exact=offers.find(p=>String(p.productId)===String(productId)),byGpuAndRegion=offers.find(p=>normalize(p.gpu)===normalize(x.productName)&&(p.regionalOffers||[]).some(o=>String(o.clusterId)===String(clusterId)||o.region===x.clusterName)),product=exact||byGpuAndRegion,regional=product?.regionalOffers?.find(o=>String(o.clusterId)===String(clusterId)||o.region===x.clusterName),regionalPrice=Number(regional?.price),basePrice=Number(product?.price),price=Number.isFinite(regionalPrice)&&regionalPrice>0?regionalPrice:Number.isFinite(basePrice)&&basePrice>0?basePrice:undefined;return{id:x.id,provider:'ppio',providerName:this.name,name:x.name,status:normalizeStatus(x.status),productId:productId||product?.productId,clusterId:clusterId||regional?.clusterId,gpu:x.productName,gpuCount:Number(x.gpuNum),image:x.imageUrl,region:x.clusterName,price,priceUnit:'CNY/hour',priceSource:regionalPrice>0?'regional-inventory':basePrice>0?'product-fallback':'unavailable',statusError:x.statusError?.message||x.statusError?.state?{state:x.statusError?.state,message:x.statusError?.message}:undefined,raw:x}});}
  async getSshConnection(id){
    const detail=await call(this.name,this.base,'/gpu-instance/openapi/v1/gpu/instance',{headers:this.headers(),query:{instanceId:id}});
    const command=String(detail.sshCommand||'').trim();
    if(!command||!detail.password)throw new ProviderError(this.name,'厂商尚未返回 SSH 登录信息，请等待实例启动完成',409);
    const portMatch=command.match(/(?:^|\s)-p\s*(\d+)(?:\s|$)/i);
    const targetMatch=command.match(/(?:^|\s)(?:ssh\s+)?(?:-[^\s]+\s+)*(?:([^@\s]+)@)?(\[[^\]]+\]|[a-z0-9._-]+)(?=\s|$)/i);
    const fallbackTarget=command.match(/([^@\s]+)@(\[[^\]]+\]|[a-z0-9._-]+)/i);
    const username=fallbackTarget?.[1]||targetMatch?.[1]||'root';
    const host=(fallbackTarget?.[2]||targetMatch?.[2]||'').replace(/^\[|\]$/g,'');
    const port=Number(portMatch?.[1]||22);
    if(!host)throw new ProviderError(this.name,'厂商返回的 SSH 命令格式无法识别',502,{sshCommand:command});
    if(port===22)throw new ProviderError(this.name,'厂商仍返回默认 SSH 端口，已拒绝展示；请等待非默认端口分配完成',409);
    return{provider:'ppio',command,username,host,port,password:String(detail.password),source:'provider-api'};
  }
  async create(o){const rootfsSize=Math.max(10,Number(o.rootfsSize)||100),telemetryPushUrl=serviceUrl(this.env,'/api/agent/telemetry'),telemetryUrl=serviceUrl(this.env,'/provision/telemetry.py'),bootstrapUrl=serviceUrl(this.env,'/provision/bootstrap.sh');const envs=[...ppioEnvs(this.env).map(x=>x.key==='BASE_URL'?{...x,value:String(x.value).trim().replace(/\/+$/,'')}:x),{key:'FLEET_PROVIDER',value:'ppio'},{key:'FLEET_INSTANCE_NAME',value:o.name},{key:'FLEET_TELEMETRY_PUSH_URL',value:telemetryPushUrl}];const startup=`curl -fsSL --retry 3 --connect-timeout 10 --max-time 60 ${shellQuote(telemetryUrl)} -o /tmp/gpu-fleet-telemetry.py || true; if test -s /tmp/gpu-fleet-telemetry.py; then nohup python3 /tmp/gpu-fleet-telemetry.py >/tmp/gpu-fleet-telemetry.log 2>&1 & fi; curl -fsSL --retry 3 --connect-timeout 10 --max-time 60 ${shellQuote(bootstrapUrl)} -o /tmp/gpu-fleet-bootstrap.sh || true; if test -s /tmp/gpu-fleet-bootstrap.sh; then bash /tmp/gpu-fleet-bootstrap.sh >/tmp/gpu-fleet-bootstrap.log 2>&1 || true; fi; exec sleep infinity`,command=`bash -lc ${shellQuote(startup)}`;const body={name:o.name,productId:o.productId,gpuNum:o.gpuCount||1,rootfsSize,imageUrl:o.imageUrl||NGC_IMAGE,ports:'3000/http',envs,command,clusterId:o.clusterId||'',networkId:'',kind:'gpu',month:0,billingMode:o.billingMode||'onDemand',autoRenew:false,minCudaVersion:this.env.PPIO_MIN_CUDA_VERSION||'13.0'};const r=await call(this.name,this.base,'/gpu-instance/openapi/v1/gpu/instance/create',{method:'POST',headers:this.headers(),body});if(!r.id)throw new ProviderError(this.name,'PPIO 创建响应缺少实例 ID',502,r);return {id:r.id,provider:'ppio',name:o.name,status:'provisioning',image:body.imageUrl,provisioning:'automatic'};}
  action(id,action){const map={start:'start',stop:'stop',delete:'delete'};return call(this.name,this.base,`/gpu-instance/openapi/v1/gpu/instance/${map[action]}`,{method:'POST',headers:this.headers(),body:{instanceId:id}});}
}

class AutoDLAdapter {
  constructor(env){this.env=env;this.name='AutoDL';this.base=env.AUTODL_API_BASE||'https://api.autodl.com';this.token=env.AUTODL_TOKEN;this.image=env.AUTODL_IMAGE_UUID;this.bootstrap=env.BASE_URL;}
  headers(){return {authorization:authRequired(this.name,this.token,'AUTODL_TOKEN'),'content-type':'application/json'};}
  async listOffers(){authRequired(this.name,this.token,'AUTODL_TOKEN');const specs=(this.env.AUTODL_GPU_SPECS||'pro6000-p').split(',');return specs.map(id=>({id:`autodl:${id}`,provider:'autodl',providerName:this.name,productId:id,gpu:id,gpuCount:1,region:'由 AutoDL 调度',price:null,priceUnit:'CNY/hour',available:true,source:'configured',note:'AutoDL Pro API 不提供统一公开报价接口，最终价格以创建响应和控制台为准'}));}
  async discover(){const r=await call(this.name,this.base,'/api/v1/dev/instance/pro/image/private/list',{method:'POST',headers:this.headers(),body:{page_index:1,page_size:100}});const products=[['h800','H800 80G 通用型'],['v-48g','4090 48G 通用型'],['pro6000-p','RTX PRO 6000 96G 性能型'],['v-32g-p','4080(S) 32G 性能型'],['v-48g-350w','3090 48G 通用型'],['5090-p','5090 32G 性能型'],['4090D','4090D 通用型']].map(([id,name])=>({id,name}));return{provider:'autodl',products,images:r.data?.list||[],selectionRequired:['productId','imageUuid'],note:'GPU 规格表来自官方 Pro API 附录；库存由创建时调度，私有镜像由账号 API 实时返回。'}}
  async listPrivateImages(){const r=await call(this.name,this.base,'/api/v1/dev/instance/pro/image/private/list',{method:'POST',headers:this.headers(),body:{page_index:1,page_size:100}});return r.data?.list||[];}
  async resolveImageUuid(requested){if(requested)return requested;if(this.image)return this.image;const images=await this.listPrivateImages();const wanted=(this.env.AUTODL_IMAGE_NAME||'gpu-fleet-cuda13').toLowerCase();const text=x=>String(x.image_name||x.name||x.imageName||'').toLowerCase();const state=x=>String(x.status||x.image_status||x.state||'').toLowerCase();const usable=x=>!state(x)||['finished','success','available','ready','normal'].some(s=>state(x).includes(s));const match=images.find(x=>text(x)===wanted&&usable(x))||images.find(x=>text(x).includes(wanted)&&usable(x));if(!match){const names=images.map(text).filter(Boolean).slice(0,8).join(', ');throw new ProviderError(this.name,`AutoDL 找不到可用私有镜像“${this.env.AUTODL_IMAGE_NAME||'gpu-fleet-cuda13'}”。请先按 README 制作并保存一次，或配置 AUTODL_IMAGE_UUID。${names?` 当前镜像：${names}`:''}`,503)}return match.image_uuid||match.uuid||match.id;}
  async listInstances(){const r=await call(this.name,this.base,'/api/v1/dev/instance/pro/list',{method:'POST',headers:this.headers(),body:{page_index:1,page_size:100}});return (r.data?.list||[]).map(x=>({id:x.uuid,provider:'autodl',providerName:this.name,name:x.name,status:normalizeStatus(x.status),gpu:x.gpu_spec_uuid,gpuCount:x.req_gpu_amount,region:x.region_name,raw:x}));}
  async create(o){const image=await this.resolveImageUuid(o.imageUuid);const body={data_center_list:o.regions,req_gpu_amount:o.gpuCount||1,expand_system_disk_by_gb:o.expandDisk||100,gpu_spec_uuid:o.productId,image_uuid:image,cuda_v_from:132,instance_name:o.name,start_command:bootstrapCommand(this.env,{extra:{FLEET_AGENT_PORT:'6008'}})};const r=await call(this.name,this.base,'/api/v1/dev/instance/pro/create',{method:'POST',headers:this.headers(),body});return{id:r.data,provider:'autodl',name:o.name,status:'provisioning',image,provisioning:'automatic-native'};}
  action(id,action){const path={start:'power_on',stop:'power_off',delete:'release'}[action];const body={instance_uuid:id};if(action==='start')body.payload='gpu';return call(this.name,this.base,`/api/v1/dev/instance/pro/${path}`,{method:'POST',headers:this.headers(),body});}
}

class RunPodAdapter {
  constructor(env){this.env=env;this.name='RunPod';this.base=env.RUNPOD_API_BASE||'https://rest.runpod.io/v1/';this.graphql=env.RUNPOD_GRAPHQL_BASE||'https://api.runpod.io/';this.token=env.RUNPOD_API_KEY;}
  headers(){return{authorization:`Bearer ${authRequired(this.name,this.token,'RUNPOD_API_KEY')}`,'content-type':'application/json'};}
  async listOffers(){const query=`query FleetGpuTypes { gpuTypes { id displayName memoryInGb lowestPrice(input: { gpuCount: 1, secureCloud: true }) { stockStatus uninterruptablePrice availableGpuCounts } } }`;const r=await call(this.name,this.graphql,'/graphql',{method:'POST',headers:this.headers(),body:{query}});if(r.errors?.length)throw new ProviderError(this.name,r.errors[0].message,502,r.errors);return(r.data?.gpuTypes||[]).filter(x=>x.id.startsWith('NVIDIA ')).map(x=>({id:`runpod:${x.id}`,provider:'runpod',providerName:this.name,productId:x.id,gpu:x.displayName||x.id,gpuCount:1,vram:x.memoryInGb,region:'Secure Cloud 自动调度',price:Number(x.lowestPrice?.uninterruptablePrice||0),priceUnit:'USD/hour',available:x.lowestPrice?.stockStatus==='High'||(x.lowestPrice?.availableGpuCounts||[]).length>0,inventory:x.lowestPrice?.stockStatus,source:'live'}));}
  async discover(){return{provider:'runpod',products:await this.listOffers(),selectionRequired:['productId'],defaults:{cloudType:'SECURE',imageName:NGC_IMAGE,cuda:'13.0',ports:['3000/http']}}}
  async listInstances(){const pods=await call(this.name,this.base,'pods',{headers:this.headers(),query:{computeType:'GPU',includeMachine:true}});return(pods||[]).filter(x=>x.desiredStatus!=='TERMINATED').map(x=>{const mappings=x.portMappings||x.runtime?.ports||{},wanted=Number(this.env.FLEET_SSH_PORT||22022),mapping=Array.isArray(mappings)?mappings.find(p=>Number(p.privatePort||p.containerPort||p.internalPort||p.port)===wanted):undefined,externalPort=Array.isArray(mappings)?Number(mapping?.publicPort||mapping?.externalPort||mapping?.hostPort):Number(mappings[String(wanted)]);return{id:x.id,provider:'runpod',providerName:this.name,name:x.name,status:normalizeStatus(x.desiredStatus),gpu:x.gpu?.displayName||x.machine?.gpuDisplayName,gpuCount:x.gpu?.count||x.machine?.minPodGpuCount||1,region:x.machine?.dataCenterId||x.machine?.location,image:x.image,price:Number(x.adjustedCostPerHr||x.costPerHr||0),priceUnit:'USD/hour',agentUrl:`https://${x.id}-3000.proxy.runpod.net`,sshHost:x.publicIp||x.publicIP||x.machine?.publicIp,sshPort:externalPort||undefined,sshUser:'root',raw:x}});}
  async create(o){const env=Object.fromEntries(ppioEnvs(this.env).map(({key,value})=>[key,value])),sshPort=Number(this.env.FLEET_SSH_PORT||22022);env.FLEET_SSH_PORT=String(sshPort);env.FLEET_SSH_PUBLIC_KEY=o.sshPublicKey;env.FLEET_SSH_USER='root';const provisionEnv={...this.env,FLEET_SSH_PORT:String(sshPort),FLEET_SSH_PUBLIC_KEY:o.sshPublicKey,FLEET_SSH_USER:'root'},body={name:o.name||'gpu-fleet',cloudType:o.cloudType||'SECURE',computeType:'GPU',containerDiskInGb:o.rootfsSize||100,volumeInGb:o.volumeSize||100,volumeMountPath:'/workspace',imageName:o.imageUrl||NGC_IMAGE,allowedCudaVersions:['13.0'],gpuCount:o.gpuCount||1,gpuTypeIds:[o.productId],gpuTypePriority:'custom',interruptible:Boolean(o.spot),globalNetworking:false,supportPublicIp:true,ports:['3000/http',`${sshPort}/tcp`],env,dockerEntrypoint:['bash','-lc'],dockerStartCmd:[bootstrapCommand(provisionEnv,{keepAlive:true})],minDiskBandwidthMBps:o.minDiskBandwidthMBps||500,minDownloadMbps:o.minDownloadMbps||100};const r=await call(this.name,this.base,'pods',{method:'POST',headers:this.headers(),body});return{id:r.id,provider:'runpod',name:r.name||body.name,status:normalizeStatus(r.desiredStatus||'RUNNING'),image:r.image||body.imageName,price:Number(r.adjustedCostPerHr||r.costPerHr||0),provisioning:'automatic-container',agentUrl:`https://${r.id}-3000.proxy.runpod.net`};}
  action(id,action){if(action==='delete')return call(this.name,this.base,`pods/${encodeURIComponent(id)}`,{method:'DELETE',headers:this.headers()});return call(this.name,this.base,`pods/${encodeURIComponent(id)}/${action}`,{method:'POST',headers:this.headers()});}
}

class HyperstackAdapter {
  constructor(env){this.env=env;this.name='Hyperstack';this.base=env.HYPERSTACK_API_BASE||'https://infrahub-api.nexgencloud.com/v1/';this.token=env.HYPERSTACK_API_KEY;}
  headers(){return{api_key:authRequired(this.name,this.token,'HYPERSTACK_API_KEY'),'content-type':'application/json'};}
  async listOffers(){const [flavorResponse,priceResponse]=await Promise.all([call(this.name,this.base,'core/flavors',{headers:this.headers()}),call(this.name,this.base,'pricebook',{headers:this.headers()})]);if(flavorResponse.status===false)throw new ProviderError(this.name,flavorResponse.message||'获取 GPU flavors 失败',502,flavorResponse);const normalize=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]/g,'');const pricebook=Array.isArray(priceResponse)?priceResponse:[];const prices=new Map(pricebook.map(x=>[normalize(x.name),Number(x.value||0)]));return(flavorResponse.data||[]).flatMap(group=>(group.flavors||[]).filter(x=>x.gpu).map(x=>{const region=x.region_name||group.region_name;const gpuCount=Number(x.gpu_count||1);const unitPrice=prices.get(normalize(x.gpu))||prices.get(normalize(x.name))||0;return{id:`hyperstack:${x.name}:${region}`,provider:'hyperstack',providerName:this.name,productId:x.name,gpu:x.gpu,gpuCount,cpu:Number(x.cpu||0),ram:Number(x.ram||0),disk:Number(x.disk||0),region,price:unitPrice*gpuCount,priceUnit:'USD/hour',priceSource:'pricebook',available:Boolean(x.stock_available),inventory:x.stock_available?'high':'none',deployable:Boolean(x.stock_available),supportsHibernation:!x.features?.no_hibernation,source:'live',note:'启动后自动验证 CUDA 13.2；用户允许时可降级到 CUDA 12.8'}}));}
  async discover(){return{provider:'hyperstack',products:await this.listOffers(),selectionRequired:['productId','region'],defaults:{containerImage:NGC_IMAGE},note:'cloud-init 根据宿主驱动自动选择 NGC 26.03/CUDA 13.2 或获准的 25.03/CUDA 12.8。'};}
  environmentFor(region){if(this.env.HYPERSTACK_ENVIRONMENTS){let map;try{map=JSON.parse(this.env.HYPERSTACK_ENVIRONMENTS)}catch{throw new ProviderError(this.name,'HYPERSTACK_ENVIRONMENTS 必须是 region 到 environment 的 JSON 对象',503)}if(map[region])return map[region]}return this.env.HYPERSTACK_ENVIRONMENT;}
  async listInstances(){const r=await call(this.name,this.base,'core/virtual-machines',{headers:this.headers()});if(r.status===false)throw new ProviderError(this.name,r.message||'获取实例失败',502,r);return(r.instances||[]).map(x=>({id:String(x.id),provider:'hyperstack',providerName:this.name,name:x.name,status:normalizeStatus(x.status),gpu:x.flavor?.gpu,gpuCount:Number(x.flavor?.gpu_count||1),region:x.environment?.region,image:x.image?.name,price:null,priceUnit:'USD/hour',ip:x.floating_ip,agentUrl:x.floating_ip?`http://${x.floating_ip}:3000`:undefined,cudaProfile:'自动检测中',raw:x}));}
  async create(o){const environment=this.environmentFor(o.region);const keyName=this.env.HYPERSTACK_KEY_NAME,imageName=this.env.HYPERSTACK_IMAGE_NAME;if(!environment||!keyName||!imageName||!this.env.HYPERSTACK_AGENT_CIDR)throw new ProviderError(this.name,'缺少 HYPERSTACK_ENVIRONMENT(S)、HYPERSTACK_KEY_NAME、HYPERSTACK_IMAGE_NAME 或 HYPERSTACK_AGENT_CIDR',503);if(!this.env.FLEET_BOOTSTRAP_URL)throw new ProviderError(this.name,'缺少 FLEET_BOOTSTRAP_URL，无法自动装机',503);const values=Object.fromEntries(ppioEnvs(this.env).map(({key,value})=>[key,value]));values.FLEET_SSH_PORT=String(this.env.FLEET_SSH_PORT||22022);values.FLEET_SSH_PUBLIC_KEY=o.sshPublicKey;values.FLEET_SSH_USER='ubuntu';values.FLEET_ALLOW_CUDA128_FALLBACK=o.allowCuda128Fallback?'1':'0';values.FLEET_PROVISION_TOKEN=o.provisionToken;values.FLEET_PROVISION_STATUS_URL=new URL('/api/provision/hyperstack-status',this.env.FLEET_BOOTSTRAP_URL).href;values.FLEET_CONTAINER_IMAGE_CUDA13=this.env.FLEET_CONTAINER_IMAGE_CUDA13||'nvcr.io/nvidia/pytorch:26.03-py3';values.FLEET_CONTAINER_IMAGE_CUDA128=this.env.FLEET_CONTAINER_IMAGE_CUDA128||'nvcr.io/nvidia/pytorch:25.03-py3';const exports=Object.entries(values).map(([k,v])=>`export ${k}=${shellQuote(v)}`).join('; ');const installer=new URL('/provision/hyperstack.sh',this.env.FLEET_BOOTSTRAP_URL).href;const userData=`#!/bin/bash\nset -Eeuo pipefail\n${exports}\ncurl -fsSL --retry 5 ${shellQuote(installer)} -o /tmp/gpu-fleet-hyperstack.sh\nbash /tmp/gpu-fleet-hyperstack.sh\n`;const body={count:1,environment_name:environment,flavor_name:o.productId,key_name:keyName,name:o.name||'gpu-fleet',image_name:imageName,assign_floating_ip:true,enable_port_randomization:false,user_data:userData};if(this.env.HYPERSTACK_AGENT_CIDR)body.security_rules=[{direction:'ingress',protocol:'tcp',port_range_min:Number(values.FLEET_SSH_PORT),port_range_max:Number(values.FLEET_SSH_PORT),ethertype:'IPv4',remote_ip_prefix:this.env.HYPERSTACK_AGENT_CIDR}];const r=await call(this.name,this.base,'core/virtual-machines',{method:'POST',headers:this.headers(),body});if(r.status===false)throw new ProviderError(this.name,r.message||'创建 VM 失败',502,r);const instance=r.instances?.[0];return{id:String(instance?.id),provider:'hyperstack',name:instance?.name||body.name,status:'provisioning',image:body.image_name,cudaProfile:o.allowCuda128Fallback?'优先 CUDA 13.2，允许降级 12.8':'必须 CUDA 13.2',provisioning:'cloud-init-container'};}
  action(id,action){if(action==='delete')return call(this.name,this.base,`core/virtual-machines/${encodeURIComponent(id)}`,{method:'DELETE',headers:this.headers()});const operation=action==='start'?'restore':'hibernate';return call(this.name,this.base,`core/virtual-machines/${encodeURIComponent(id)}/${operation}`,{headers:this.headers()});}
}
const hyperstackListInstances=HyperstackAdapter.prototype.listInstances;
HyperstackAdapter.prototype.listInstances=async function(){return(await hyperstackListInstances.call(this)).map(instance=>{if(!instance.ip)return instance;return{...instance,agentUrl:undefined,sshHost:instance.ip,sshPort:Number(this.env.FLEET_SSH_PORT||22022),sshUser:this.env.FLEET_SSH_USER||'ubuntu'}})};
const hyperstackCreate=HyperstackAdapter.prototype.create;
HyperstackAdapter.prototype.create=async function(options){this.env.FLEET_PROVIDER='hyperstack';this.env.FLEET_INSTANCE_NAME=options.name||'gpu-fleet';this.env.FLEET_TELEMETRY_PUSH_URL=serviceUrl(this.env,'/api/agent/telemetry');return hyperstackCreate.call(this,options)};
function adapters(env=process.env){return {ppio:new PpioAdapter(env),hyperstack:new HyperstackAdapter(env),runpod:new RunPodAdapter(env)};}
module.exports={adapters,ProviderError,normalizeStatus,ppioPriceToCny};
