const { NGC_IMAGE, serviceUrl } = require('../../provisioning');
const { hyperstackStartup } = require('./startup');
const { ProviderError, call, normalizeStatus, authRequired } = require('../common/http');

class HyperstackAdapter {
  constructor(env){this.env=env;this.name='Hyperstack';this.base=env.HYPERSTACK_API_BASE||'https://infrahub-api.nexgencloud.com/v1/';this.token=env.HYPERSTACK_API_KEY;}
  headers(){return{api_key:authRequired(this.name,this.token,'HYPERSTACK_API_KEY'),'content-type':'application/json'};}
  async configurationResources(){const [environmentResponse,keypairResponse,imageResponse]=await Promise.all([call(this.name,this.base,'core/environments',{headers:this.headers(),query:{pageSize:100}}),call(this.name,this.base,'core/keypairs',{headers:this.headers(),query:{pageSize:100}}),call(this.name,this.base,'core/images',{headers:this.headers(),query:{pageSize:100}})]);const environments=environmentResponse.environments||environmentResponse.data||[],environmentRegions=new Map(environments.map(x=>[x.name,x.region])),keypairs=keypairResponse.keypairs||keypairResponse.data||[],imageGroups=imageResponse.images||imageResponse.data||[],rawImages=imageGroups.flatMap(group=>Array.isArray(group.images)?group.images.map(image=>({...image,region_name:image.region_name||group.region_name})):group),imagesByName=new Map();for(const x of rawImages){const name=x.name||x.image_name;if(!name)continue;const regions=x.regions||x.region_names||(x.region_name?[x.region_name]:[]),existing=imagesByName.get(name);if(existing)existing.regions=[...new Set([...existing.regions,...regions])];else imagesByName.set(name,{id:x.id,name,regions:[...regions],labels:x.labels||[]})}return{environments:environments.map(x=>({id:x.id,name:x.name,region:x.region})),keypairs:keypairs.map(x=>{const environmentName=x.environment?.name||x.environment_name;return{id:x.id,name:x.name,environmentName,region:x.environment?.region||x.region||environmentRegions.get(environmentName),fingerprint:x.fingerprint}}),images:[...imagesByName.values()]};}
  async importKeypair({name,environmentName,publicKey}){const r=await call(this.name,this.base,'core/keypairs',{method:'POST',headers:this.headers(),body:{name,environment_name:environmentName,public_key:publicKey}});if(r.status===false)throw new ProviderError(this.name,r.message||'创建 SSH Keypair 失败',502,r);return r.keypair||r.keypairs?.[0]||r.data||{name,environment:{name:environmentName}};}
  async deleteKeypair(id){const r=await call(this.name,this.base,`core/keypair/${encodeURIComponent(id)}`,{method:'DELETE',headers:this.headers()});if(r?.status===false)throw new ProviderError(this.name,r.message||'删除 SSH Keypair 失败',502,r);return r;}
  async listOffers(){const [flavorResponse,priceResponse]=await Promise.all([call(this.name,this.base,'core/flavors',{headers:this.headers()}),call(this.name,this.base,'pricebook',{headers:this.headers()})]);if(flavorResponse.status===false)throw new ProviderError(this.name,flavorResponse.message||'获取 GPU flavors 失败',502,flavorResponse);const normalize=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]/g,'');let configuredRegions=[];try{configuredRegions=JSON.parse(this.env.HYPERSTACK_REGIONS||'[]')}catch{}if(!configuredRegions.length&&this.env.HYPERSTACK_REGION)configuredRegions=[this.env.HYPERSTACK_REGION];const pricebook=Array.isArray(priceResponse)?priceResponse:[];const prices=new Map(pricebook.map(x=>[normalize(x.name),Number(x.value||0)]));return(flavorResponse.data||[]).flatMap(group=>(group.flavors||[]).filter(x=>x.gpu&&(!configuredRegions.length||configuredRegions.includes(x.region_name||group.region_name))).map(x=>{const region=x.region_name||group.region_name;const gpuCount=Number(x.gpu_count||1);const unitPrice=prices.get(normalize(x.gpu))||prices.get(normalize(x.name))||0;return{id:`hyperstack:${x.name}:${region}`,provider:'hyperstack',providerName:this.name,productId:x.name,gpu:x.gpu,gpuCount,cpu:Number(x.cpu||0),ram:Number(x.ram||0),disk:Number(x.disk||0),region,price:unitPrice*gpuCount,priceUnit:'USD/hour',priceSource:'pricebook',available:Boolean(x.stock_available),inventory:x.stock_available?'high':'none',deployable:Boolean(x.stock_available),supportsHibernation:!x.features?.no_hibernation,source:'live',note:'启动后自动验证 CUDA 13.2；用户允许时可降级到 CUDA 12.8'}}));}
  async discover(){return{provider:'hyperstack',products:await this.listOffers(),selectionRequired:['productId','region'],defaults:{containerImage:NGC_IMAGE},note:'cloud-init 根据宿主驱动自动选择 NGC 26.03/CUDA 13.2 或获准的 25.03/CUDA 12.8。'};}
  environmentFor(region){if(this.env.HYPERSTACK_ENVIRONMENTS){let map;try{map=JSON.parse(this.env.HYPERSTACK_ENVIRONMENTS)}catch{throw new ProviderError(this.name,'HYPERSTACK_ENVIRONMENTS 必须是 region 到 environment 的 JSON 对象',503)}if(map[region])return map[region]}return this.env.HYPERSTACK_ENVIRONMENT;}
  async listInstances(){const r=await call(this.name,this.base,'core/virtual-machines',{headers:this.headers()});if(r.status===false)throw new ProviderError(this.name,r.message||'获取实例失败',502,r);return(r.instances||[]).map(x=>{const ip=x.floating_ip||x.floatingIp||x.public_ip||x.publicIp||null,user=this.env.HYPERSTACK_IMAGE_USER;return{id:String(x.id),provider:'hyperstack',providerName:this.name,name:x.name,status:normalizeStatus(x.status),providerStatus:x.status||'unknown',providerSubStatus:x.sub_status||x.subStatus||'',gpu:x.flavor?.gpu,gpuCount:Number(x.flavor?.gpu_count||1),region:x.environment?.region,image:x.image?.name,price:null,priceUnit:'USD/hour',ip,publicIp:Boolean(ip),accessType:'ssh',sshHost:ip||undefined,sshPort:22,sshUser:user,sshCommand:ip?`ssh -i <private-key> ${user}@${ip}`:undefined,accessMessage:ip?'Floating IP 可直接通过 SSH 访问':'正在等待 Hyperstack 分配 Floating IP',cudaProfile:'自动检测中',raw:x}});}
  async create(o){const environment=o.environmentName||this.environmentFor(o.region),keyName=o.keyName||this.env.HYPERSTACK_KEY_NAME,imageName=this.env.HYPERSTACK_IMAGE_NAME,imageUser=this.env.HYPERSTACK_IMAGE_USER;if(!environment||!keyName||!imageName||!imageUser)throw new ProviderError(this.name,'运行商配置未完成',503);const startup=hyperstackStartup(this.env,o),sshCidr=this.env.HYPERSTACK_AGENT_CIDR||'0.0.0.0/0';const body={count:1,environment_name:environment,flavor_name:o.productId,key_name:keyName,name:o.name||'fast-gpu',image_name:imageName,assign_floating_ip:true,security_rules:[{direction:'ingress',protocol:'tcp',port_range_min:startup.sshPort,port_range_max:startup.sshPort,ethertype:'IPv4',remote_ip_prefix:sshCidr}],user_data:startup.userData};const r=await call(this.name,this.base,'core/virtual-machines',{method:'POST',headers:this.headers(),body});if(r.status===false)throw new ProviderError(this.name,r.message||'创建 VM 失败',502);const instance=r.instances?.[0];return{id:String(instance?.id),provider:'hyperstack',name:instance?.name||body.name,status:'provisioning',image:body.image_name,publicIp:false,accessType:'ssh',sshPort:startup.sshPort,sshUser:imageUser,accessMessage:'正在等待 Hyperstack 分配 Floating IP 并通过 SSH 初始化',cudaProfile:o.expectedCudaMajor===12?'CUDA 12.8':o.allowCuda128Fallback?'优先 CUDA 13.2，允许降级 12.8':'必须 CUDA 13.2',provisioning:'ssh-orchestrated'};}
  action(id,action){if(action==='delete')return call(this.name,this.base,`core/virtual-machines/${encodeURIComponent(id)}`,{method:'DELETE',headers:this.headers()});const operation={start:'start',stop:'stop'}[action];if(!operation)throw new ProviderError(this.name,`不支持的 VM 操作：${action}`,400);return call(this.name,this.base,`core/virtual-machines/${encodeURIComponent(id)}/${operation}`,{headers:this.headers()});}
}
const hyperstackListInstances=HyperstackAdapter.prototype.listInstances;
HyperstackAdapter.prototype.listInstances=async function(){return hyperstackListInstances.call(this)};
const hyperstackCreate=HyperstackAdapter.prototype.create;
HyperstackAdapter.prototype.create=async function(options){this.env.FLEET_PROVIDER='hyperstack';this.env.FLEET_INSTANCE_NAME=options.name||'fast-gpu';if(this.env.BASE_URL)this.env.FLEET_TELEMETRY_PUSH_URL=serviceUrl(this.env,'/api/agent/telemetry');return hyperstackCreate.call(this,options)};

module.exports = { HyperstackAdapter };
