const http=require('node:http'),{execFile,execFileSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
const run=(cmd,args,timeout=120000)=>new Promise(resolve=>execFile(cmd,args,{timeout,maxBuffer:8e6},(error,stdout,stderr)=>resolve({ok:!error,stdout:String(stdout).trim(),stderr:String(stderr).trim()})));
function resolveExecutable(name,extra=[]){const candidates=[process.env[name.toUpperCase()+'_PATH'],...String(process.env.PATH||'').split(path.delimiter).map(dir=>path.join(dir,name)),...extra].filter(Boolean);try{const loginPath=execFileSync('/bin/bash',['-lc','command -v '+name],{encoding:'utf8',timeout:5000}).trim();if(loginPath)candidates.unshift(loginPath)}catch{}return candidates.find(file=>{try{fs.accessSync(file,fs.constants.X_OK);return true}catch{return false}})||null}
const nvbandwidthPath=resolveExecutable('nvbandwidth',['/usr/local/bin/nvbandwidth','/usr/bin/nvbandwidth','/opt/nvbandwidth/nvbandwidth','/opt/nvbandwidth/build/nvbandwidth','/workspace/nvbandwidth/build/nvbandwidth']);
function versionOf(file,args=['--version']){if(!file)return null;try{return execFileSync(file,args,{encoding:'utf8',timeout:10000,stdio:['ignore','pipe','pipe']}).trim().split('\n')[0]||null}catch{return null}}
function inspectTools(){const definitions=[['codex','Codex CLI',[]],['claude','Claude Code',[]],['nvbandwidth','nvbandwidth',['/usr/local/bin/nvbandwidth','/usr/bin/nvbandwidth']],['fio','fio',[]],['rclone','rclone',[]],['node','Node.js',[]]];return definitions.map(([id,label,extra])=>{const executable=id==='nvbandwidth'?nvbandwidthPath:resolveExecutable(id,extra);return{id,label,installed:Boolean(executable),path:executable,version:versionOf(executable)}})}
const installedTools=inspectTools();
function bandwidthStatus(){const installed=Boolean(nvbandwidthPath);let lastRun=null,results=null;try{const report=JSON.parse(fs.readFileSync('/var/lib/gpu-fleet/benchmark.json','utf8'));lastRun=report.generatedAt||null;results=report.nvbandwidth||null}catch{}return{installed,path:nvbandwidthPath,lastRun,results}}
async function telemetry(){const q=await run('nvidia-smi',['--query-gpu=index,name,utilization.gpu,memory.used,memory.total,temperature.gpu,power.draw','--format=csv,noheader,nounits']);const gpus=q.stdout.split('\n').filter(Boolean).map(line=>{const [index,name,util,memoryUsed,memoryTotal,temperature,power]=line.split(',').map(x=>x.trim());return{index:+index,name,util:+util,memoryUsed:+memoryUsed,memoryTotal:+memoryTotal,temperature:+temperature,power:+power}}),error=q.ok?undefined:{component:'nvidia-smi',code:'gpu_telemetry_collection_failed',message:q.stderr||q.stdout||'nvidia-smi 执行失败'};return{ts:Date.now(),gpus,tools:installedTools,load:require('node:os').loadavg(),memory:{free:require('node:os').freemem(),total:require('node:os').totalmem()},error}}
const csvLines=s=>s.split('\n').filter(Boolean).map(line=>line.split(',').map(x=>x.trim()));
const reachabilityTargets={huggingface:'https://huggingface.co',cloudflare:'https://www.cloudflare.com',aws:'https://aws.amazon.com',openai:'https://api.openai.com/v1/models',google:'https://www.google.com/generate_204'};
async function testReachability(){
  const targets={};
  for(const [name,url] of Object.entries(reachabilityTargets)){const probe=await run('curl',['--noproxy','*','-o','/dev/null','-sS','-w','%{http_code}|%{remote_ip}|%{time_namelookup}|%{time_connect}|%{time_appconnect}|%{time_total}','--connect-timeout','8','--max-time','20',url]);const [status,remoteIp,dns,connect,tls,total]=probe.stdout.split('|');targets[name]={url,proxyBypassed:true,reachable:/^[234]/.test(status),status:Number(status)||0,remoteIp,dnsMs:+dns*1000,connectMs:+connect*1000,tlsMs:+tls*1000,totalMs:+total*1000,error:probe.ok?'':probe.stderr}}
  const result={generatedAt:new Date().toISOString(),mode:'direct-origin',explicitProxyBypassed:true,allReachable:Object.values(targets).every(x=>x.reachable),targets,note:'Origin probes run inside the GPU instance with curl --noproxy *. Cloud NAT is a normal direct egress path; transparent network intermediaries cannot be ruled out by curl alone.'};
  fs.mkdirSync('/var/lib/gpu-fleet',{recursive:true});fs.writeFileSync('/var/lib/gpu-fleet/reachability.json',JSON.stringify(result,null,2));return result
}
async function benchmark(mode='quick'){
  const full=mode==='full',fioSize=full?'2G':'256M',downloadBytes=full?'100000000':'20000000';
  const gpu=await run('nvidia-smi',['--query-gpu=index,name,pci.bus_id,pcie.link.gen.current,pcie.link.gen.max,pcie.link.width.current,pcie.link.width.max','--format=csv,noheader,nounits']);
  const nvlink=await run('nvidia-smi',['nvlink','-s']);const topology=await run('nvidia-smi',['topo','-m']);const bandwidth=nvbandwidthPath?await run(nvbandwidthPath,['-j'],300000):{ok:false,stdout:'',stderr:'nvbandwidth executable not found in Agent PATH or known install locations'};
  const gpuCount=csvLines(gpu.stdout).length,ncclScript='/tmp/gpu-fleet-nccl-check.py';
  let nccl={ok:false,skipped:gpuCount<2,error:gpuCount<2?'single GPU':''};
  if(gpuCount>1){fs.writeFileSync(ncclScript,"import torch, torch.distributed as dist\ndist.init_process_group('nccl')\nx=torch.tensor([1.0],device='cuda')\ndist.all_reduce(x)\nassert x.item()==dist.get_world_size()\nif dist.get_rank()==0: print('NCCL all_reduce passed on %d GPUs' % dist.get_world_size())\ndist.destroy_process_group()\n");const check=await run('torchrun',['--standalone',`--nproc_per_node=${gpuCount}`,ncclScript],120000);try{fs.unlinkSync(ncclScript)}catch{}nccl={ok:check.ok,skipped:false,output:check.stdout,error:check.stderr||(!check.ok?'NCCL all_reduce failed':'')}}
  fs.mkdirSync('/data',{recursive:true});const diskFile='/data/.gpu-fleet-fio';
  const disk=await run('fio',['--name=fleet','--filename='+diskFile,'--size='+fioSize,'--rw=readwrite','--rwmixread=50','--bs=1M','--direct=1','--iodepth=16','--ioengine=libaio','--output-format=json'],300000);
  const download=await run('curl',['--noproxy','*','--fail','-sS','-o','/dev/null','-w','%{speed_download}','--connect-timeout','10','--max-time','120','https://speed.cloudflare.com/__down?bytes='+downloadBytes]);
  const upload=await run('curl',['--noproxy','*','--fail','-sS','-o','/dev/null','-w','%{speed_upload}','--connect-timeout','10','--max-time','120','-X','POST','--data-binary','@'+diskFile,'https://speed.cloudflare.com/__up']);try{fs.unlinkSync(diskFile)}catch{}
  const reachabilityResult=await testReachability(),reachability=reachabilityResult.targets;
  let fio=null,nvbandwidth=null;try{fio=JSON.parse(disk.stdout)}catch{}try{nvbandwidth=JSON.parse(bandwidth.stdout)}catch{}const diskJob=fio?.jobs?.[0];
  const report={generatedAt:new Date().toISOString(),gpus:csvLines(gpu.stdout).map(([index,name,busId,genCurrent,genMax,widthCurrent,widthMax])=>({index:+index,name,busId,pcie:{genCurrent:+genCurrent,genMax:+genMax,widthCurrent:+widthCurrent,widthMax:+widthMax}})),nccl,nvlink:{ok:nvlink.ok,raw:nvlink.stdout,error:nvlink.stderr},topology:{ok:topology.ok,raw:topology.stdout,error:topology.stderr},nvbandwidth:nvbandwidth||{available:false,error:bandwidth.stderr||'nvbandwidth did not return valid JSON'},disk:{target:'/data',ok:disk.ok&&!!fio,readMBps:(diskJob?.read?.bw_bytes||0)/1e6,writeMBps:(diskJob?.write?.bw_bytes||0)/1e6,readIops:diskJob?.read?.iops||0,writeIops:diskJob?.write?.iops||0,raw:fio,error:disk.ok?'':disk.stderr},internet:{downloadMbps:download.ok?Number(download.stdout)*8/1e6:null,uploadMbps:upload.ok?Number(upload.stdout)*8/1e6:null,downloadError:download.ok?'':download.stderr,uploadError:upload.ok?'':upload.stderr,direct:true,proxyBypassed:true},reachability,note:'Measured inside the GPU instance. Multi-GPU instances run a real NCCL all_reduce; GPU memory is not treated as one automatically merged pool.'};fs.mkdirSync('/var/lib/gpu-fleet',{recursive:true});fs.writeFileSync('/var/lib/gpu-fleet/benchmark.json',JSON.stringify(report,null,2));return report
}
function profile(){try{return JSON.parse(fs.readFileSync('/var/lib/gpu-fleet/profile.json','utf8'))}catch{return{status:'provisioning',phase:'awaiting_bootstrap',phaseLabel:'正在等待初始化脚本'}}}
function controlUrl(pathname){const base=process.env.BASE_URL||process.env.FLEET_TELEMETRY_PUSH_URL;return base?new URL(pathname,base).href:null}
function agentHeaders(){return{'content-type':'application/json','x-fleet-agent-id':process.env.FLEET_AGENT_ID||'',authorization:`Bearer ${process.env.FLEET_AGENT_SECRET||''}`}}
let jobRunning=false;async function executeAgentJob(job){if(jobRunning||!job)return;jobRunning=true;const provider=process.env.FLEET_PROVIDER||'unknown',instanceName=process.env.FLEET_INSTANCE_NAME,agentId=process.env.FLEET_AGENT_ID,headers=agentHeaders();try{let result;if(job.type==='benchmark')result=await benchmark(job.params?.mode);else throw Error(`unsupported agent job type: ${job.type}`);await fetch(controlUrl('/api/agent/job-result'),{method:'POST',headers,body:JSON.stringify({agentId,provider,instanceName,jobId:job.id,status:'completed',result}),signal:AbortSignal.timeout(30000)})}catch(error){await fetch(controlUrl('/api/agent/job-result'),{method:'POST',headers,body:JSON.stringify({agentId,provider,instanceName,jobId:job.id,status:'failed',error:error.message}),signal:AbortSignal.timeout(15000)}).catch(()=>{})}finally{jobRunning=false}}
let telemetryPushing=false;async function pushTelemetry(){if(telemetryPushing||!process.env.FLEET_TELEMETRY_PUSH_URL||!process.env.FLEET_INSTANCE_NAME)return;telemetryPushing=true;try{const response=await fetch(process.env.FLEET_TELEMETRY_PUSH_URL,{method:'POST',headers:agentHeaders(),body:JSON.stringify({agentId:process.env.FLEET_AGENT_ID,provider:process.env.FLEET_PROVIDER||'unknown',instanceName:process.env.FLEET_INSTANCE_NAME,capabilities:['agent_jobs'],telemetry:{...await telemetry(),runtime:profile()}}),signal:AbortSignal.timeout(15000)}),payload=await response.json().catch(()=>({}));if(!response.ok)throw Error(`HTTP ${response.status}: ${payload.error||response.statusText}`);if(payload.job&&!jobRunning)void executeAgentJob(payload.job)}catch(error){console.error('telemetry push failed:',error.message)}finally{telemetryPushing=false}}
if(process.env.FLEET_TELEMETRY_PUSH_URL){setTimeout(pushTelemetry,1000);setInterval(pushTelemetry,3000).unref()}
http.createServer(async(req,res)=>{res.setHeader('content-type','application/json');try{if(process.env.FLEET_AGENT_SECRET&&req.headers.authorization!==`Bearer ${process.env.FLEET_AGENT_SECRET}`){res.statusCode=401;return res.end(JSON.stringify({error:'unauthorized'}))}if(req.url==='/health')return res.end(JSON.stringify({ok:true,runtime:profile()}));if(req.url==='/telemetry')return res.end(JSON.stringify({...await telemetry(),runtime:profile()}));if(req.url==='/reachability'&&req.method==='POST')return res.end(JSON.stringify(await testReachability()));if(req.url==='/reachability'&&fs.existsSync('/var/lib/gpu-fleet/reachability.json'))return res.end(fs.readFileSync('/var/lib/gpu-fleet/reachability.json'));if(req.url==='/benchmark'&&req.method==='POST')return res.end(JSON.stringify({...await benchmark(),runtime:profile()}));if(req.url==='/benchmark'&&fs.existsSync('/var/lib/gpu-fleet/benchmark.json'))return res.end(fs.readFileSync('/var/lib/gpu-fleet/benchmark.json'));res.statusCode=404;res.end(JSON.stringify({error:'not found'}))}catch(e){res.statusCode=500;res.end(JSON.stringify({error:e.message}))}}).listen(Number(process.env.FLEET_AGENT_PORT||3000),'0.0.0.0');
